
title: 한 미술교육
desctiption: 한 미술은 양재동에 있는 좋은 학원.
url: https://han-art.github.io/
permalink: ':title/'

markdown: kramdown
baseurl: "/"
full-version: "https://han-art.github.io/"

sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: Han Art Education

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
